// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Click_Button_To_Customize_Output_Folder : HelpFeature
	{
		public Click_Button_To_Customize_Output_Folder()
		{
			MinVersion = HelpFeatureVersion.v0_4_WirsingKopf;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "click button to customize output folder";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can change output folder for new recordings by clicking on the folder-button next to the recording path in the main window."
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "NOTE: To do this you need to have the output path control enabled (Context Menu-> 'Show Output Path Control')"
				}
			};
		}
	}
}
