// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Click_Button_To_Open_Selected_File_In_Explorer : HelpFeature
	{
		public Click_Button_To_Open_Selected_File_In_Explorer()
		{
			MinVersion = HelpFeatureVersion.v0_2_preRelease;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "click button to open selected file in explorer";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can select the currently selected file in the windows explorer by clicking the folder-button at the bottom left of the main window."
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "NOTE: If there is no file selected this will just open the output folder."
				}
			};
		}
	}
}
