// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Click_Tray_Icon_To_Restore_Main_Window_From_Tray : HelpFeature
	{
		public Click_Tray_Icon_To_Restore_Main_Window_From_Tray()
		{
			MinVersion = HelpFeatureVersion.v0_3_release;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "click tray icon to restore main window from tray";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "When RecNForget is running in the background, you can double-click its tray icon to show the main window."
				}
			};
		}
	}
}
