// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Click_Button_To_ExportAsMp3 : HelpFeature
	{
		public Click_Button_To_ExportAsMp3()
		{
			MinVersion = HelpFeatureVersion.v0_6_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "click button to export as mp3";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can export the selected file as mp3 by clicking the export button right next the selected file name in the Selected File Control"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "Export Bitrate can be set in Settings -> Output -> Mp3 Export Settings -> Bitrate"
				},
				new HelpFeatureDetailLine()
				{
					Content = "The exported filename will be automatically generated from the selected original file."
				},
				new HelpFeatureDetailLine()
				{
					Content = "If you want to be prompted for an export name you can enable the \"prompt for exported file name\"-dialog under"
				},
				new HelpFeatureDetailLine()
				{
					Content = "Settings -> Output -> Mp3 Export Settings"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "NOTE: To do this you need to have the selected file control enabled (Context Menu-> 'Show Selected File Control')"
				}
			};
		}
	}
}
