// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Customize_SelectedFileControlVisibility : HelpFeature
	{
		public Customize_SelectedFileControlVisibility()
		{
			MinVersion = HelpFeatureVersion.v0_5_____;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "customize selected file control visibility";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "The Selected File Control provides quick access to file manipulation and information:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- show selected file name"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- show selected file size and play length"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- rename the selected file"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- delete the selected file"
				},
				new HelpFeatureDetailLine()
				{
					Content = "(this is control is disabled by default)"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "To enable or disable the Selected File Control:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- open the menu at the top left of the main window"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- click on 'Selected File Control'"
				}
			};
		}
	}
}
