// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Customize_RecordingTimerControlVisibility : HelpFeature
	{
		public Customize_RecordingTimerControlVisibility()
		{
			MinVersion = HelpFeatureVersion.v0_6_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "customize recording timer control visibility";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "The Recording Timer Control can be shown in the main window - this allows"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- automatic recording stop after a given time"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- delayed recording start after a given time"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- time spans are entered right to left (seconds first) in the following format: d:hh:mm:ss"
				},
				new HelpFeatureDetailLine()
				{
					Content = "(this is control is disabled by default)"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "- if the \"Stops after\"- timer is enabled, a recording session  will be automatically ended after that time span"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- \"stop recording\" can still be forced by hitting record again (if \"Stops after\"- timer is already running)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- \"Stops after\" can also be enabled while already recording"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "- if the \"Starts after\"- timer is enabled, the \"start recording\" action will be delayed by that time span"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- \"start recording\" can be forced by triggering record again (if \"Starts after\"- timer is already running)"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "To enable or disable the Recording Timer Control:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- open the menu at the top left of the main window"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- click on 'Show Recording Timer Control'"
				}
			};
		}
	}
}
