// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Customize_WindowTheme : HelpFeature
	{
		public Customize_WindowTheme()
		{
			MinVersion = HelpFeatureVersion.v0_6_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "customize window theme";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can change how RecNForget windows look."
				},
				new HelpFeatureDetailLine()
				{
					Content = "Right now there is a simple white and a simple black style."
				},
				new HelpFeatureDetailLine()
				{
					Content = "To change your window style open the context menu:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "Context Menu -> Theme -> (Select Theme)"
				}
			};
		}
	}
}
