// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Customize_Export_Output_Folder : HelpFeature
	{
		public Customize_Export_Output_Folder()
		{
			MinVersion = HelpFeatureVersion.v0_6;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "customize mp3 export output folder";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can change the output folder RecNForget puts exported mp3 files into."
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "To change this setting:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- open the menu at the top left of the main window"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- click on 'Open Settings' -> Output"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- click on the setting 'Export folder'"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- select the export folder you desire"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- exit the settings window by pressing the accept button"
				}
			};
		}
	}
}
