// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Fix_DialogWindowsWithoutUpperBorder : HelpFeature
	{
		public Fix_DialogWindowsWithoutUpperBorder()
		{
			MinVersion = HelpFeatureVersion.v0_6;
			FeatureClass = HelpFeatureClass.BugFix;
			Title = "Custom dialog windows do not show excessive borders on top";
		}
	}
}
