// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Fix_FilePrefixDidntAffectDisplayedFileNames : HelpFeature
	{
		public Fix_FilePrefixDidntAffectDisplayedFileNames()
		{
			MinVersion = HelpFeatureVersion.v0_4_WirsingKopf;
			FeatureClass = HelpFeatureClass.BugFix;
			Title = "file prefix changes affect displayed file name";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "changing the file prefix now also changes the displayed file name with output path"
				}
			};
		}
	}
}
