// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class FunFact_ChiliGarlicShrimps : HelpFeature
	{
		public FunFact_ChiliGarlicShrimps()
		{
			MinVersion = HelpFeatureVersion.v0_5_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.FunFact;
			Title = "Garlic chili shrimps:";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "Remember, always have enough bread to soak up the delicious oil!"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "Ingredients: (1 serving)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 250g shrimp, raw, peeled, deveined,"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Not too little garlic,"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Enough red chilies (dried or fresh),"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Few handful of cherry tomatoes,"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Thyme & other herbs"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Oil (e.g. canola oil)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- baguette"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "Preparation:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Garlic freshly peeled, mash in oil"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Add shrimps, a little salt, fry with a lot of oil"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Chop chili as needed and add to the shrimps"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Should fry only a few minutes"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Shortly before the end add pureed garlic in oil/brush shrimps in"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Continue frying only briefly (garlic can burn quickly)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Add cherry tomatoes and herbs"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- Eat"
				}
			};
		}
	}
}
