// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Info_GoDark05 : HelpFeature
	{
		public Info_GoDark05()
		{
			Priority = 999;
			MinVersion = HelpFeatureVersion.v0_5_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.Information;
			Title = "Going with the times, RecNForget now can go dark, too.";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "Figuratively :-)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "If you like you can now toggle RecNForget's layout between light and dark theme:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "Context Menu -> Theme -> (Select Theme)"
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "For now there is only light and dark as themes, feel free to propose other color combinations, I might add them :-)"
				}
			};
		}
	}
}
