// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Press_Hotkey_To_StopRecording_And_Save : HelpFeature
	{
		public Press_Hotkey_To_StopRecording_And_Save()
		{
			MinVersion = HelpFeatureVersion.v0_1_preRelease;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "press hotkey to stop recording and save";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can stop recording audio and save as a new file by pressing the hotkey you assigned to 'Toggle Record'."
				},
				new HelpFeatureDetailLine()
				{
					Content = "This hotkey is global, meaning it also works when the main window is not focused."
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "This hotkey is set to [Pause] by default."
				}
			};
		}
	}
}
