// <auto-generated />
using System.Collections.Generic;

namespace RecNForget.Help.Features
{
	public class Press_Hotkey_To_ExportAsMp3 : HelpFeature
	{
		public Press_Hotkey_To_ExportAsMp3()
		{
			MinVersion = HelpFeatureVersion.v0_5_ChiliGarlicShrimps;
			FeatureClass = HelpFeatureClass.NewFeature;
			Title = "press hotkey to export as mp3";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "You can export the selected file as mp3 by pressing the [X] key."
				},
				new HelpFeatureDetailLine()
				{
					Content = "This hotkey only works when the main window is in focus."
				},
				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "Export Bitrate can be set in Settings -> Output -> Mp3 Export Settings -> Bitrate"
				},
				new HelpFeatureDetailLine()
				{
					Content = "The exported filename will be automatically generated from the selected original file."
				},
				new HelpFeatureDetailLine()
				{
					Content = "If you want to be prompted for an export name you can enable the \"prompt for exported file name\"-dialog under"
				},
				new HelpFeatureDetailLine()
				{
					Content = "Settings -> Output -> Mp3 Export Settings"
				}
			};
		}
	}
}
