// <auto-generated />
using RecNForget.Services.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RecNForget.Help.Features
{
	public class FunFact_Wirsingkopf : HelpFeature
	{
		public FunFact_Wirsingkopf()
		{
			MinVersion = HelpFeatureVersion.v0_4_WirsingKopf;
			FeatureClass = HelpFeatureClass.FunFact;
			Title = "Wirsingkopf";
			HelpLines = new List<HelpFeatureDetailLine>()
			{
				new HelpFeatureDetailLine()
				{
					Content = "Ingredients: (6-8 servings)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 1 large pot (min 5 L), 1-2 pans to fry the ingredients"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 150 g bacon cubes"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 250 g minced meat (mixed pork/beef)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 700 g kassler"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 1,5 kg savoy cabbage"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 3 red peppers"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 2 yellow peppers"
				},new HelpFeatureDetailLine()
				{
					Content = "- 3 carrots"
				},new HelpFeatureDetailLine()
				{
					Content = "- 1 bunch spring onion"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 6 onions"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 7 cloves of garlic"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 8 small red chillies"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 750 ml vegetable broth"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 500 ml milk"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- 300 g cheese spread"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- white wine"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- cream for cooking"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- sour cream"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- salt"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- pepper"
				},
				new HelpFeatureDetailLine()
				{
					Content = "- caraway seeds"
				},


				new HelpFeatureDetailLine()
				{
					Content = string.Empty
				},
				new HelpFeatureDetailLine()
				{
					Content = "Preparation:"
				},
				new HelpFeatureDetailLine()
				{
					Content = "1. chop up all ingredients, but keep them separate"
				},
				new HelpFeatureDetailLine()
				{
					Content = "2. chop up savoy cabbage into small bits and put it in a large saucepan (min 5 L) together with oil and braise on a low-medium flame."
				},
				new HelpFeatureDetailLine()
				{
					Content = "3. stir the savoy cabbage frequently ... as soon as it collapses and begins to brown, add wine and some vegetable broth (not all 750 ml)."
				},
				new HelpFeatureDetailLine()
				{
					Content = "4. sear the kassler, deglaze, add to the savoy cabbage, (it can take a long time for the pork loin to brown, if necessary hold the kassler pan separately and sear other ingredients in a separate pan)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "5. grill the peppers and carrots in parallel in a pan and then add them to the savoy cabbage"
				},
				new HelpFeatureDetailLine()
				{
					Content = "6. fry onions, garlic and chilli in a pan and then add to the savoy cabbage"
				},
				new HelpFeatureDetailLine()
				{
					Content = "7. sear the bacon cubes and minced meat, deglaze and add to the savoy cabbage"
				},
				new HelpFeatureDetailLine()
				{
					Content = "8. continue to fill up with vegetable broth, add spring onion and milk, turn up the flame for cooking"
				},
				new HelpFeatureDetailLine()
				{
					Content = "9. stir in cheese spread, add cream for desired consistency, if necessary further dilute with wine/vegetable broth/milk"
				},
				new HelpFeatureDetailLine()
				{
					Content = "10. season with plenty of caraway seeds"
				},
				new HelpFeatureDetailLine()
				{
					Content = "11. add salt and pepper (maybe also nutmeg and kukurma)"
				},
				new HelpFeatureDetailLine()
				{
					Content = "12. bring to the boil ... finished!"
				},
				new HelpFeatureDetailLine()
				{
					Content = "13. stir in the sour cream according to your taste on your plate"
				}
			};
		}
	}
}
