name: release test

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'a message'
        default: 'triggered manually?'
        
jobs:
  test:
        runs-on: windows-latest
        steps:
                - name: logging
                  run: echo 'logging something'
                - name: releasing
                  uses: ncipollo/release-action@v1
                  with:
                    tag: 'testTag0815'
                    body: "This is the body of the release"
                    draft: true
