name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore RecNForget.sln
    - name: Nerdbank.GitVersioning
      with:
        setAllVars: true
      uses: AArnott/nbgv@v0.3
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
    - run: echo "NBGV_AssemblyFileVersion $NBGV_AssemblyFileVersion"
      # with:
        # The path to the directory for which the version should be determined. This should be at or below the directory containing the version.json file. Default is repo root directory.
        # path: # optional, default is .
        # Defines ALL version variables as environment variables, with a "NBGV_" prefix.
        # setAllVars: # optional
        # Defines a few common version variables as environment variables, with a "Git" prefix (e.g. GitBuildVersion, GitBuildVersionSimple, GitAssemblyInformationalVersion).
        # setCommonVars: # optional
        # The version of the nbgv dotnet CLI tool to install and use. If not specified, the default is the latest stable version.
        # toolVersion: # optional
    - name: Build and Publish
      run: msbuild RecNForget.Setup\RecNForget.Setup.wixproj /p:Configuration=Release /p:PublicRelease=true
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: RecNForget_TestBuild
        path: RecNForget.Setup\bin\Release
